### ISSUE TITLE
Rotation inverted? 🤔 

### ISSUE THREAD

**Issue by gomezzz** [rasmusmarak/TOSS#49]
Was wondering, shouldn't we need to rotate the point in the opposite direction as the bodies rotation? 🤔 

https://github.com/rasmusmarak/TOSS/blob/2501351468eb362fa9ec8217b2fc426db37fca9a/toss/trajectory/equations_of_motion.py#L81

Might be wrong, just to doublecheck

**Comment by rasmusmarak** [comment]
I did some plots and checks with pen and paper to verify this and it seems to make sense in the cases I formulated to use an inverse rotation. What probably got me rethinking the concept before was certain edge cases, such as when the satellite is either moving much slower or faster than the angular rotation of the body. I have fixed this issue in PR #51 since it relates to the rotation around the spin axis, and also since it is a very small change codewise.
